Add unauthorized-handler to opts
subvisual/dictator pull request #32
Opened 2021-10-14 17:42 UTC by joseemds

closes #25

2021-10-19 10:38 UTC, frm requested changes

2021-10-19 10:38 UTC, frm commented on lib/dictator.ex
> -      unauthorized_handler = unauthorized_handler()
Thank you for your help! Can we add a test for this specific case?

2021-10-19 23:01 UTC, joseemds commented
@frm tests added!

2021-10-20 09:33 UTC, frm approved these changes
Looks great! Thanks!

2021-10-20 09:33 UTC, merged